### ISSUE TITLE
SDL2 not working examples

### ISSUE THREAD

**Issue by Nazariglez** [Nazariglez/nae#39]
Some of the examples are not working with SDL2 or not works exactly in the same way that using winit.

- [ ] fullscreen (Resize wrong, could be related to the DPI render_projection)
- [ ] mask (Not working at all)
- [ ] mask2 (Not working at all)
- [ ] mask3 (Not working at all)
- [ ] mouse4 (Movement speeds is way slower than winit)
- [ ] screen_scale (not rendering while the user resize, maybe its something about sdl that cannot be fixed)

These errors are not from the examples but from the renderer or the sdl impl.

**Comment by SirVer** [comment]
@Nazariglez Why was this closed? I am very interested in exploring using Notan rendering into SDL2 on an embedded device.

**Comment by Nazariglez** [comment]
Hello, no one has ever (but me) used SDL with notan, so I removed it and embraced winit. Still, a SDL backend is doable by the users, however, I am not sure if future versions should support creating custom backends because it seems to not be being used and it complicates the design of the lib. Although I am open to any suggestions.

**Comment by SirVer** [comment]
I cannot really advise... I will not invest time into building out my application with Notan, since I need to run it on an embedded device that only has KSMDRM support, no X or wayland. Since Notan cannot serve this space currently without SDL2 support, the overhead of building an app 'just to try' is too high.

**Comment by Nazariglez** [comment]
It makes sense to me. I am inclined towards not adding SDL2 for now. Thank you for your answer!

**Comment by SirVer** [comment]
That makes sense to me for your project. Thank you for your consideration and good luck for it going forward!
